* 2022-03-25

Added support for =pre-hook= and =post-hook= actions for commands.

The =CLIGON:COMMAND= class now accepts the =:pre-hook= and
=:post-hook= initargs, which allows specifying a function to be
invoked before and after the respective handler of the command is
executed.

The generic function =CLINGON:APPLY-HOOKS= have been added, which
takes care of applying the =pre-hook= and =post-hook= hooks.

Version of =clingon= system has been bumped to 0.3.5.

* 2022-03-24

Add support for grouping related options into categories.

The =:category= initarg for =CLINGON:OPTION= is used for specifying
the option's category.

New option kind has been added - =:list/filepath=.

The =clingon-demo= and =clingon-intro= binaries are now installed into
the =bin/= directory.

Additional utility functions have been implemented as part of the
=CLINGON.UTILS= package.

=clingon= system updated to version 0.3.3.

* 2021-12-26

=clingon= system updated to version v0.3.1.

Added support for =FILEPATH= option kinds.

* 2021-11-19

Added support for Zsh completions.

=clingon= system version bumped to v0.3.0.

* 2021-07-26

Initial release of =clingon= version v0.1.0.
