FROM clfoundation/sbcl:2.1.7 as builder

ENV QUICKLISP_ADD_TO_INIT_FILE=true

WORKDIR /root/quicklisp/local-projects/clingon
COPY . .
RUN /usr/local/bin/install-quicklisp && \
    sbcl \
      --eval '(ql:quickload :clingon.demo)' \
      --eval '(asdf:make :clingon.demo)' \
      --eval '(quit)'

FROM debian:bullseye-slim
WORKDIR /app
RUN apt-get update && apt-get install -y bash-completion
COPY --from=builder /root/quicklisp/local-projects/clingon/clingon-demo .
COPY --from=builder /root/quicklisp/local-projects/clingon/extras/completions.bash .
ENTRYPOINT ["./clingon-demo"]
